### ISSUE TITLE
[Amélioration] - Transformer en composant

### ISSUE THREAD

**Issue by Benoit382** [racacax/XML-TV-Fr#10]
Bonjour, 

Je souhaiterais integrer votre projet dans un de mes projets, via un `composer require` par exemple, seriez vous d'accord pour que je m'occupe de ce changement via une PR (modification de la structure des fichiers, ajout des namespace, ajout de tests ... ) ?

Merci d'avance.

**Comment by racacax** [comment]
Bonjour,
Bien sûr, ce serait avec plaisir. Toute contribution est la bienvenue 👍 
Merci beaucoup

**Comment by Benoit382** [comment]
Voici une premier jets pour transformer le projet en bundle, il y a encore plusieurs modif a faire #12

**Comment by Benoit382** [comment]
J'ai fait une mise a jour de la pull request

**Comment by racacax** [comment]
Merci pour cette contribution, je regarderai ça dans les prochains jours :)
