### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Systemator** [racacax/XML-TV-Fr#11]
Bonjour,
J'ai constaté un petit bug, lors de la suppression des anciens fichiers xmltv. Ils ont un nom différences lorsqu'on l'a changé dans config.json , guides_to_generate , filename.
Et sur la présentation du Github, une autre erreur dans Configuration du programme (config.json). La virgule est après le commentaire sur la ligne "enable_zip". J'ai bien galéré avant de la trouver. Mais pas de soucis, merci pour cet excellent travail.

**Comment by racacax** [comment]
Bonjour,
Merci du retour, je vais jeter un oeil :)

**Comment by Benoit382** [comment]
Cette issues est terminée pour moi.
