### ISSUE TITLE
php error

### ISSUE THREAD

**Issue by myB0B** [racacax/XML-TV-Fr#15]
2 nouveaux bugs pour la version 2.1.0 avec un cache vide (fresh install)

php warning pour de  multiples chaines :

[EPG GRAB] DiscoveryFamily.fr (52/265) : 2022-01-19PHP Warning:  unlink(var/cache/DiscoveryFamily.fr_2022-01-19.xml): No such file or directory in /home/admin/xmltv/src/Component/CacheFile.php on line 44
 | OK - SFR

et surtout php error pour certaines : 

[EPG GRAB] CanalPlusFormula1.fr (34/267) : 2022-01-22PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function racacax\XmlTv\ValueObject\DummyChannel::__construct(), 2 passed in /home/admin/xmltv/src/Component/Generator.php on line 137 and exactly 4 expected in /home/admin/xmltv/src/ValueObject/DummyChannel.php:9
Stack trace:
#0 /home/admin/xmltv/src/Component/Generator.php(137): racacax\XmlTv\ValueObject\DummyChannel->__construct()
#1 /home/admin/xmltv/example/script_all.php(24): racacax\XmlTv\Component\Generator->generateEpg()
#2 {main}
  thrown in /home/admin/xmltv/src/ValueObject/DummyChannel.php on line 9

**Comment by Benoit382** [comment]
Je regarde.

**Comment by myB0B** [comment]
Ca ne corrige pas le problème suivant : 

[EPG GRAB] Gong.fr (77/264) : 2022-01-29PHP Fatal error:  Uncaught TypeError: html_entity_decode(): Argument #1 ($string) must be of type string, bool given in /home/admin/xmltv/src/Component/Provider/AbstractProvider.php:70
Stack trace:
#0 /home/admin/xmltv/src/Component/Provider/AbstractProvider.php(70): html_entity_decode()
#1 /home/admin/xmltv/src/Component/Provider/TeleLoisirs.php(25): racacax\XmlTv\Component\Provider\AbstractProvider->getContentFromURL()
#2 /home/admin/xmltv/src/Component/Generator.php(116): racacax\XmlTv\Component\Provider\TeleLoisirs->constructEPG()
#3 /home/admin/xmltv/example/script_all.php(24): racacax\XmlTv\Component\Generator->generateEpg()
#4 {main}
  thrown in /home/admin/xmltv/src/Component/Provider/AbstractProvider.php on line 70

**Comment by Benoit382** [comment]
@racacax a corrigé le warning.
Par contre, le DummyChannel attend sa validation.

**Comment by Benoit382** [comment]
Cette issues est terminée pour moi.
