### ISSUE TITLE
teleloisirs hs

### ISSUE THREAD

**Issue by myB0B** [racacax/XML-TV-Fr#17]
[EPG GRAB] Gong.fr (77/264) : 2022-01-29PHP Fatal error:  Uncaught TypeError: html_entity_decode(): Argument #1 ($string) must be of type string, bool given in /home/admin/xmltv/src/Component/Provider/AbstractProvider.php:70
Stack trace:
#0 /home/admin/xmltv/src/Component/Provider/AbstractProvider.php(70): html_entity_decode()
#1 /home/admin/xmltv/src/Component/Provider/TeleLoisirs.php(25): racacax\XmlTv\Component\Provider\AbstractProvider->getContentFromURL()
#2 /home/admin/xmltv/src/Component/Generator.php(116): racacax\XmlTv\Component\Provider\TeleLoisirs->constructEPG()
#3 /home/admin/xmltv/example/script_all.php(24): racacax\XmlTv\Component\Generator->generateEpg()
#4 {main}
  thrown in /home/admin/xmltv/src/Component/Provider/AbstractProvider.php on line 70

**Comment by Benoit382** [comment]
@racacax Une PR pour corriger Télé Loisirs

**Comment by Benoit382** [comment]
@myB0B As tu retester ?

**Comment by racacax** [comment]
@Benoit382 De mon côté, c'est très bien passé à la dernière récupération des programmes (alors que c'était HS les dernière fois) donc problème réglé 👍
