### ISSUE TITLE
Décalage d'une heure 

### ISSUE THREAD

**Issue by Systemator** [racacax/XML-TV-Fr#19]
Bonjour,
Il y a un décalage d'une heure (le journal de 13h et de 20h, sont à 12h et 19h) avec Orange, Sfr et TeleZ.
Pas de décalage avec TeleLoisirs et Télérama.
Par contre sur Télérama, les numéros des épisodes ne sont pas correctes. Ils ont tous le numéro de saison. Je ne sais pas si cela proviens de Télérama ou d'un bug du programme.

**Comment by racacax** [comment]
Bonjour,
Je n'ai pas remarqué de décalage sur aucun de ces Provider. De mon côté ça charge bien les bonnes horaires que ce soit chez moi en France ou sur un serveur à l'étranger.
Voici un exemple avec Orange : 
`<programme start="20220201130000 +0100" stop="20220201134000 +0100" channel="France2.fr">
<title lang="fr">Journal 13h00</title>
<desc lang="fr">
Tous les jours, à 13h, la rédaction de France 2 propose un point sur l'actualité. Les informations nationales et internationales sont passées à la loupe et mises en perspective, illustrées par des reportages sur le terrain.
</desc>
<category lang="fr">Info-Météo</category>
<category lang="fr">Information</category>
<icon src="https://proxymedia.woopic.com/340/p/43_EMI_19299955.jpg"/>
<rating system="CSA">
<value>Tout public</value>
</rating>
</programme>`
Pour les bugs d'épisodes, le problème vient bien de l'API Telerama (d'où la baisse de priorité récente du service récemment).

**Comment by Benoit382** [comment]
Un décalage d'une heure, ça sent le probleme de timezone.
@Systemator peux tu nous dire ce que retourne :
```SHELL
 php -r "echo date_default_timezone_get();"     
```

**Comment by Benoit382** [comment]
@racacax Deux solutions
- Deplacer `date_default_timezone_set('Europe/Paris');` avant `$generator->generateEpg()` dans le fichier `example/script_all.php`
- Gerer la timezone directement dans les providers

Je prefere la solution Deux, mais demande plus de temps.

**Comment by Systemator** [comment]
> la commante me retourne : UTC

**Comment by Systemator** [comment]
> l

**Comment by Systemator** [comment]
la commante me retourne : UTC

**Comment by Systemator** [comment]
> * Deplacer `date_default_timezone_set('Europe/Paris');` avant `$generator->generateEpg()` dans le fichier `example/script_all.php`

J' ai fait cette correction et c'est ok pour moi, plus de décalage . Quand je reviens au code initial, il y a un décalage : 
  <programme start="20220203200000 +0100" stop="20220203204500 +0100" channel="TF1.fr">
    <title lang="fr">Journal</title>
    <desc lang="fr">Aucune description</desc>
    <category lang="fr">Journal</category>
    <icon src="http://static-cdn.tv.sfr.net/data/img/pl/6/0/8/2457806.jpg"/>
    <rating system="CSA">
      <value>Tout public</value>
    </rating>
  </programme>

**Comment by Benoit382** [comment]
J'ai pas compris concernant le décalage.
Pour mettre un exemple de code ou tu peux l'entourer de ` ``` `

**Comment by Systemator** [comment]
> J'ai pas compris concernant le décalage. Pour mettre un exemple de code ou tu peux l'entourer de `` ``` ``

erreur, mauvais copie, redited

**Comment by Systemator** [comment]
J'ai modifié comme tu as suggéré : 
`
$generator = $configurator->getGenerator();
date_default_timezone_set('Europe/Paris');
$generator->generateEpg();
$generator->exportEpg($configurator->getOutputPath());
$generator->clearCache($configurator->getCacheMaxDays());

//Logger::clearLog();
//date_default_timezone_set('Europe/Paris');
`
et ça résout bien le problème

**Comment by Benoit382** [comment]
La dernière mise a jour a corrigé le probleme, je te laisse fermer l'issue.
