### ISSUE TITLE
Installation sur Nas synology

### ISSUE THREAD

**Issue by romain211289** [racacax/XML-TV-Fr#20]
Bonjour,

Tout d'abord merci pour le taf ! Je travail actuellement avec l'ancienne version qui est déjà top !

En regardant, j'ai vu la nouvelle version du script, par contre il n'existe pas d'autre solution que de passer par composer.

Je m'explique, sur nas je sais accéder via Putty mais je voudrais éviter la modification du php.ini de ma version PHP principale installée. Or pour installer composer, je doit passer par là..

Pense tu que je pourrais installer le script sur mon pc (en windows, et basculer le script installer sur mon nas ?)

Merci

**Comment by Benoit382** [comment]
Bonjour @romain211289 
En theorie, tu peux faire le composer install sur ton poste est copier les fichiers sur le nas (le dossier vendor).
J'ai un doute avec l'utilsation de windows, mais cela se tente.

Mais si tu as un message d'erreur concernant l'installation sur le nas, je veux bien connaitre le message.

**Comment by Benoit382** [comment]
@romain211289 est tu la ?

**Comment by Benoit382** [comment]
@racacax, Je pense que tu peux fermer cette issue.
