### ISSUE TITLE
problème avec eurosport

### ISSUE THREAD

**Issue by simpledork47** [racacax/XML-TV-Fr#22]
bonsoir

j'ai remarqué qu'il n'y a pas d'entrée epg  pour eurosport1 et eurosport2
le xml provient de https://xmltvfr.fr/

en regardant une entrée, on voit que "start" et "stop" sont à la même valeur

 < programme start="20220330050000 +0200" stop="20220330050000 +0200" channel="Eurosport1.fr">
   <title lang="fr">Cyclisme : Classic Bruges-La Panne</title>
    <desc lang="fr">Aucune description</desc>

du coup j'imagine que le client ne considère pas ça comme valide et n'affiche rien, 
mais je peux me tromper

merci

**Comment by simpledork47** [comment]
https://xmltvfr.fr/xmltvreader.php?channel=Eurosport1.fr&guide=france

**Comment by racacax** [comment]
Bonjour,
Effectivement c'est étrange, je vais regarder quelle source pose ce problème

**Comment by racacax** [comment]
Ca devrait être résolu dès demain lors de la nouvelle récupération des programmes (voir dernière release)
