### ISSUE TITLE
MyCuisine

### ISSUE THREAD

**Issue by simpledork47** [racacax/XML-TV-Fr#23]
L'epg de la chaine "MyCuisine" 

c'est visible ici
https://xmltvfr.fr/xmltvreader.php?channel=MyCuisine.fr&guide=france

on dirait que c'est plutot l'epg d'une chaine qui diffuse du 'esport' / jeux video 
=> rien à voir avec la chaine

**Comment by simpledork47** [comment]
c'est l'epg de ES1 

< programme start="20220401200000 +0200" stop="20220401210000 +0200" channel="MyCuisine.fr">
    < title lang="fr">eLigue 1</title>
   < desc lang="fr">La saison 2022 de la eLigue 1 est sur MGG TV.</desc>
    < category lang="fr">Divertissement</category>
   < icon src="https://images.voomotion.be/Events/2022/02/28/49/1764170_A.jpg"/>
 < /programme>

**Comment by simpledork47** [comment]
La raison : la chaîne n'existe plus
https://www.planetecsat.com/my-cuisine-cest-fini/

**Comment by racacax** [comment]
merci de l'info, je supprimerai l'info des différents fichiers (si l'ID est celui de ES1, pour certaines sources, l'ID a dû être réutilisé)
