### ISSUE TITLE
Fichier config.json non pris en compte

### ISSUE THREAD

**Issue by b0b33140** [racacax/XML-TV-Fr#30]
Bonjour,
Quand je lance la récupération des programmes, j'ai l'erreur ci-dessous et me fichier config.json n'est pas pris en compte.

19:59 ⚡ C/4T ⚡ /var/www/XML-TV-Fr > root:$ php script_all.php
[CHARGEMENT] Chargement du fichier de config
[CHARGEMENT] Liste des paramètres : PHP Warning:  Invalid argument supplied for foreach() in /var/www/XML-TV-Fr/src/Configurator.php on line 259

Mon fichier config.json : 

{
  "days" : 4, // Nombre de jours de l'EPG
  "cache_max_days": 4, // Nombre de jours de cache
  "output_path": "./xmltv/", // Chemin de destination du XML final
  "time_limit": 0, // Temps d'éxécution max du script (0=illimité)
  "memory_limit": -1, // Quantité de mémoire vive max (-1=illimité)
  "delete_raw_xml": false, // Supprimer le XML brut après génération (true|false)
  "enable_gz": false, // Activer la compression gz (true|false)
  "enable_zip": false, // Activer la compression zip (true|false),
  "enable_dummy" : false, // Afficher un EPG mire en cas d'absence de guide pour une chaine
  "custom_priority_orders" : {"Telerama": 0.1, "Teleloisirs": 0.2, "Mycanal": 0.3}, // Modifier l'ordre de priorité pour certains services globalement
  "guides_to_generate" : [{"channels": "./channels.json", "filename": "xmltv.xml"}] // liste des XML à générer. Pour chaque élément, `channels` indique le fichier des chaines et `filename` le nom du fichier de sortie
}

**Comment by racacax** [comment]
Bonjour,
Effectivement, c'est mal remplis.
La priorité d'un provider est noté avec un nombre flottant entre 0 et 1.
Plus le nombre est proche de 1, plus la priorité est forte. Pour info,
Orange a une priorité de 0.85 par défaut, ce qui est la priorité la plus
forte de tous les Provider donc cela explique tout. Pour faire passer
devant Orange les autres providers, il faut soit diminuer la priorité
d'Orange, soit augmenter les autres.

N'hésite pas s'il y a encore un problème 🙂

**Comment by b0b33140** [comment]
Bonjour, nickel tous fonctionne! Vous pouvez fermer cette issue.
