### ISSUE TITLE
Installation sur NAS QNAP

### ISSUE THREAD

**Issue by b0b33140** [racacax/XML-TV-Fr#32]
Bonjour,
Je viens de m'offrir un NAS QNAP, php7.3 est préinstallé dessus mais je ne sais pas si toutes les extensions le sont (php7.3-mbstring php7.3-curl php7.3-zip php7.3-xml). L'installation de composer semble compliquée, pourriez-vous m'aider à faire fonctionner XML-TV-Fr sur mon NAS ?

![Screenshot_4](https://user-images.githubusercontent.com/1975795/175765364-d6415f4f-c052-4124-9f33-f3198d22d16e.png)

**Comment by Benoit382** [comment]
Bonjour, peux tu donné plus d'info sur ton nas ?
(Model +version)

**Comment by b0b33140** [comment]
![IMG_20220627_130511](https://user-images.githubusercontent.com/1975795/175927793-a17b2c5d-ec21-497b-bf23-2b30f3998bdc.jpg)

**Comment by b0b33140** [comment]
Bonjour,
Merci pour ces réponses, je vais essayer tous ses ces week-ends. Je viens de télécharger container-station mais j'avoue que ça me dépasse un peu. J’espère que la première solution va fonctionner :crossed_fingers: .

**Comment by b0b33140** [comment]
Bonjour,
Tout fonctionne correctement en copiant l'installation faite sur un autre ordinateur , vous pouvez fermer l'issue et merci pour ton aide Benoit382.

**Comment by Benoit382** [comment]
@racacax je te laisse fermer l'issue.

**Comment by racacax** [comment]
Bonjour,
Merci beaucoup @Benoit382 d'avoir traité l'issue
