### ISSUE TITLE
Mise à jour des chaines CANAL+ : Fin de C+ Décalé et arrivée de C+ Sport 360

### ISSUE THREAD

**Issue by Killmax** [racacax/XML-TV-Fr#34]
Bonjour,

Je viens de tester votre projet sur mon Jellyfin et cela fonctionne bien, merci beaucoup !

Je tenais à vous donner une informatiuon pour le fichier public que vous proposez sur votre site : 
Canal+ Décalé n'existe plus depuis le 30 aout, et il est remplacé par Canal+ Sport 360, ce qui fait que le programme actuel de Canal+ Décalé n'est pas à jour (il renvoie celui de TF1).

Je n'ai pas vu de méthode pour faire ce changement via une PR, mais je serai ravi de le faire si besoin.

**Comment by RabSsS01** [comment]
Bonjour,

Voici d'autre chaines CANAL qu'il pourrait être interressant de rajouter.

- Canal+ foot : https://www.programme-tv.net/programme/chaine/programme-canalplus-foot-11508.html
- Canal + Formule 1 : https://www.programme-tv.net/programme/chaine/programme-canalplus-formula-1-10503.html
- Canal + première league : https://www.programme-tv.net/programme/chaine/programme-canalplus-premier-league-10506.html

Merci d'avance !

**Comment by racacax** [comment]
Bonjour
Merci de l'info pour C+foot. Les autres chaînes sont déjà présentes
cependant.
