### ISSUE TITLE
Nouvelle chaîne canal+ foot, à quand l'ajout ?

### ISSUE THREAD

**Issue by poiluepistache** [racacax/XML-TV-Fr#38]
Bonjour, Canal+ Foot ne figure pas parmi les chaînes présente sur xmltv, serait t'il possible de l'ajouter ? Merci d'avance.

**Comment by racacax** [comment]
Bonjour,
Je regarderai ce week-end si des sources possède cette chaine.

**Comment by racacax** [comment]
Canal+Foot était bien présent dans le repo. pas ajouté sur xmltvfr.fr cependant. Ce sera dispo dès demain.
