### ISSUE TITLE
Beaucoup de guides TV HS

### ISSUE THREAD

**Issue by petitsurfeur** [racacax/XML-TV-Fr#4]
Bonjour

J'ai installé ton script, c'est génial mais j'ai pas mal de guides TV HS. Les ID Telerama sont pourtant corrects. 
Exemples avec les chaines Cine+

"CinePlusEmotion.fr":{"failed_providers":["Telerama","PlayTV","Voo","Tele7Jours","Orange","TVHebdo","Afrique","TV5Style","UltraNature"],"success":false},
"CinePlusFamiz.fr":{"failed_providers":["Telerama","PlayTV","Voo","Tele7Jours","Orange","TVHebdo","Afrique","TV5Style","UltraNature"],"success":false},
"CinePlusFrisson.fr":{"failed_providers":["Telerama","PlayTV","Voo","Tele7Jours","Orange","TVHebdo","Afrique","TV5Style","UltraNature"],"success":false},
"CineFX.fr":{"failed_providers":["Telerama","PlayTV","Voo","Tele7Jours","Orange","TVHebdo","Afrique","TV5Style","UltraNature"],"success":false},
"CinePlusPremier.fr":{"failed_providers":["Telerama","PlayTV","Voo","Tele7Jours","Orange","TVHebdo","Afrique","TV5Style","UltraNature"],"success":false},

Ci-joint le fichier de log
[logs20210728153031.json.txt](https://github.com/racacax/XML-TV-Fr/files/6893618/logs20210728153031.json.txt)

**Comment by racacax** [comment]
Bonjour,
J'ai pu apporter quelques correctifs aujourd'hui (notament au service Voo) et le service PlayTV a été supprimé. Cependant, les services Telerama et Orange qui contiennent ces chaines auraient dû fonctionner. Y-a-t-il eu des erreurs dans l'éxecution du script ? Je pense par exemple à une absence du module cURL pour PHP ou d'autres librairies.
