### ISSUE TITLE
Canal+ Kids n'a plus de programme. Merci par avance.

### ISSUE THREAD

**Issue by poiluepistache** [racacax/XML-TV-Fr#40]
https://xmltvfr.fr/xmltvreader.php?channel=CanalPlusKIDS.fr
![image](https://user-images.githubusercontent.com/96775359/214433460-eb11ac0f-f5cc-4809-a1b9-ec31bb9dd18e.png)

**Comment by racacax** [comment]
Etrange effectivement, j'ajoute ça à ma liste de tâches, merci de l'info

**Comment by racacax** [comment]
Sera corrigé demain matin à la prochaine récupération des données
