### ISSUE TITLE
Eurosport 360 et événement 4k sans epg

### ISSUE THREAD

**Issue by poiluepistache** [racacax/XML-TV-Fr#46]
Bonjour, les eurosport 360 n'ont pas de programme epg. Ainsi que la chaîne EvenementsSports4KUHD.fr qui n'en n'a pas non plus. Merci par avance.

**Comment by racacax** [comment]
Bonjour,
Cela vient sûrement du fait que MyCanal bloque certaines requêtes sur mon serveur. Ca marche dans mes tests en local. J'essaierai d'installer un proxy

**Comment by poiluepistache** [comment]
Ok ça marche merci.
