### ISSUE TITLE
Canal+ KIDS, Canal+ Formula 1 et Canal+ Premier League epg impossible à lire peu importe l'application 

### ISSUE THREAD

**Issue by poiluepistache** [racacax/XML-TV-Fr#47]
Bonjour, l'epg pour les chaînes suivantes : Canal+ KIDS, Canal+ Formula 1 et Canal+ Premier League ne fonctionnent pas malgré avoir fait correspondre le tvg id au sein de mon iptv.
![Screenshot_2023-04-18-20-56-04-676_com myiptvonline implayerm](https://user-images.githubusercontent.com/96775359/232878067-5e6461b9-0e4c-4c93-8ae4-7eec7e4324bf.jpg)

**Comment by racacax** [comment]
Pour Canal+Kids, l'EPG fonctionne bien https://xmltvfr.fr/xmltvreader.php?channel=CanalPlusKIDS.fr
Pour les deux autres, l'EPG est rarement fourni car elles ne diffusent que très rarement. A voir si j'ai de meilleures sources

**Comment by poiluepistache** [comment]
Oui cela marche sur le site mais dans les applications impossible

**Comment by racacax** [comment]
je vais tester de mon côté pour voir d'où vient le problème

**Comment by poiluepistache** [comment]
Je vous remercie.

**Comment by poiluepistache** [comment]
@racacax vous me redirez si vous avez trouvé.

**Comment by poiluepistache** [comment]
@racacax Salut, j'ai trouvé d'où venait le bug sur les chaînes que je t'ai cité. Il y a bien un problème de ton côté. Je t'explique les programmes ne durent que quelques minutes sur l'epg et ensuite il y a un gros blanc d'une heure environ à chaque fois. Ça c'est pour canal+ kids. Regarde, programme de 9h48 à 10h01 puis blanc jusqu'à 10h58 :

**Comment by poiluepistache** [comment]
@racacax Salut, j'ai trouvé d'où venait le bug sur les chaînes que je t'ai cité. Il y a bien un problème de ton côté. Je t'explique les programmes ne durent que quelques minutes sur l'epg et ensuite il y a un gros blanc d'une heure environ à chaque fois. Ça c'est pour canal+ kids. Regarde, programme de 9h48 à 10h01 puis blanc jusqu'à 10h58 :
![IMG_20230422_094020_791](https://user-images.githubusercontent.com/96775359/233770476-8380b0ad-501a-4cba-8551-c31daafb25d3.jpg)
Et sur les chaînes Canal+ F1 et premier League c'est exactement le même problème sauf que le programme commence vers minuit - 1h et dure que quelque heure. Je te remercie par avance si tu pourras faire quelque chose merci.

**Comment by poiluepistache** [comment]
@racacax

**Comment by racacax** [comment]
@poiluepistache Problème corrigé. Les résultats devraient commencer à apparaitre dès demain sur https://xmltvfr.fr/

**Comment by poiluepistache** [comment]
![Screenshot_2023-05-09-18-17-47-093_com android chrome](https://github.com/racacax/XML-TV-Fr/assets/96775359/a45d6298-2fd9-4fed-8bcf-4bd197f13bb9)
Salut @racacax , alors les plages horaires sont bonnes mais aucun titre ça me met donc encore un petit bug. Sur canal+ kids, F1 et premier League toujours 😉. Merci d'avance.

**Comment by racacax** [comment]
Salut,
Assez ironiquement, c'est dû à un autre fix qui est mal passé. Le bug original venait de TéléLoisirs mais le nouveau vient de MyCanal. Auparavant, comme MyCanal ne fonctionnait pas, il passait par TéléLoisirs qui avait un bug. J'ai fix TéléLoisirs et MyCanal et comme MyCanal a la priorité devant TéléLoisirs, il est passé devant et le bug qui a été rajouté a entrainé cela. Normalement ça devrait être corrigé dès demain, c'est juste que j'ai mal mis les proxys. Si ça reste instable, je changerai les priorités probablement car MyCanal a pas l'air de très apprécier que je récupère leur guide des programmes :D.

**Comment by poiluepistache** [comment]
Cool si tu as trouvé. Merci pour ta réactivité. Je te tiens au courant demain si c'est good 😉
