### ISSUE TITLE
Est-t'il possible de mettre les France3 régionaux dans le xml TNT sur le site ?

### ISSUE THREAD

**Issue by prahal** [racacax/XML-TV-Fr#49]
Ces France3 régionaux sont bien disponibles en TNT (même si pas tous sur le même émetteur).
Si je pouvais éviter de télécharger le France complet 70Mo pour ajouter un France3 régional au listing TNT 4Mo ce serait très pratique.
Je n'ai pas trouvé de rapport fermé indiquant que c'était voulu.

**Comment by racacax** [comment]
Bonjour,
Pour les France 3, c'est le comportement attendu. Le but est d'avoir l'EPG plus minimaliste possible pour le TNT.
Dans le futur, il devrait y avoir un EPG à la carte qui permettrait de gérer les chaines que vous souhaitez sélectionner
