### ISSUE TITLE
Demande d'explication sur installation du script

### ISSUE THREAD

**Issue by romain211289** [racacax/XML-TV-Fr#5]
Bonjour,

Je me permet d'écrire une demande, je n'arrive pas à comprendre l'installation du script.
J'ai compris que mon erreur provient de channel.json que je ne dois pas bien remplir ou mettre au mauvais endroit, mais je n'arrive pas à solutionner tout seul mon problème.. 

(Cela doit etre tout simple, je me doute mais là ça m'agace de ne pas comprendre mon erreur).

A noter, le script est hebergé sur mon NAS synology. Mais cela n'a rien à voir car j'ai essayé de lancer le script sur windows et j'ai le même message..

Merci !

voici mes log : 

channels.json manquant
Warning: file_get_contents(channels.json): failed to open stream: No such file or directory in /volume1/web/scripts/EPG/script_all.php on line 75

Warning: array_keys() expects parameter 1 to be array, null given in /volume1/web/scripts/EPG/script_all.php on line 76

Warning: Invalid argument supplied for foreach() in /volume1/web/scripts/EPG/script_all.php on line 77

Warning: fopen(xmltv/xmltv.xml): failed to open stream: No such file or directory in /volume1/web/scripts/EPG/script_all.php on line 144

Warning: fwrite() expects parameter 1 to be resource, boolean given in /volume1/web/scripts/EPG/script_all.php on line 149

Warning: Invalid argument supplied for foreach() in /volume1/web/scripts/EPG/script_all.php on line 150

Warning: fwrite() expects parameter 1 to be resource, boolean given in /volume1/web/scripts/EPG/script_all.php on line 177

Warning: fclose() expects parameter 1 to be resource, boolean given in /volume1/web/scripts/EPG/script_all.php on line 178

Warning: file_put_contents(logs/logs20210926160309.json): failed to open stream: No such file or directory in /volume1/web/scripts/EPG/script_all.php on line 179

Warning: file_get_contents(xmltv/xmltv.xml): failed to open stream: No such file or directory in /volume1/web/scripts/EPG/script_all.php on line 180

Warning: file_put_contents(xmltv/xmltv.xml.gz): failed to open stream: No such file or directory in /volume1/web/scripts/EPG/script_all.php on line 182
GZ : OK
ZIP : OK

**Comment by racacax** [comment]
Bonjour,
Est-ce bien la dernière version ? Normalement, s'il n'y a pas de fichiers
channels.json, il bascule automatiquement sur le fichier
channels_example.json. Dans votre message, vous avez marqué "channel.json"
sans s, peut être aussi une erreur d'écriture ? Si le fichier
channels_example.json est toujours présent, l'erreur ne devrait tout de
même pas avoir lieu mais je demande tout de même.


Le dim. 26 sept. 2021 à 16:10, romain211289 ***@***.***> a
écrit :

**Comment by romain211289** [comment]
Il s'agit d'une erreur de frappe, j'ai bien channels.json.  C'est bien ce que j'avais compris dans le script "if channels.json don"t exist" bascule automatique sur channels-example.son. Du coup j'ai essayer de lancer le script sans rien modifier.. et même message
Je ne comprend pas du tout..

**Comment by SebMourlhou** [comment]
Hello,

Essaye en te plaçant sur le répertoire du script avant de le lancer.

`cd /volume1/web/scripts/EPG/`

**Comment by racacax** [comment]
Est-ce que le répertoire de travail dans le terminal est bien la racine du
projet ? Si vous démarrez le script depuis un autre répertoire en indiquant
le chemin du script, ça ne fonctionnera pas.

Le dim. 26 sept. 2021 à 16:28, romain211289 ***@***.***> a
écrit :

**Comment by romain211289** [comment]
Yes!!! Merci à vous deux c'est exactement ça. Il fallait que mon nas soit dans le dossier avant de lancer le script.. 

Du coup pour ceux qui voudraient mettre le script dans le NAS et créer un tache il faut enregistrer cette ligne de commande : 

cd /volume1/web/scripts/EPG/
/usr/bin/php -f /volume1/web/scripts/EPG/script_all.php >> /volume1/web/out.txt


Par contre, si je comprend bien là il me fait un EPG sur 8 jours et cherche sur toutes sources.. bref si je veux mettre sur 2 jours je dois mettre 2 dans 'config.json' et pour le choix des chaines je modifie le fichier "channels_example.json" : j'enleve les chaines non voulu et je renomme le fichier  en channels.json dans le dossier racine ? 

Dans tous les cas, BRAVO pour le boulot sur ce script, mon programme TV sera enfin nickel !

**Comment by racacax** [comment]
Parfait :)
Il suffit bien de copier channels_example.json en channels.json et de
mettre uniquement les chaines voulues. A noter que d'autres chaines sont
disponibles n'étant pas dans le fichier d'exemple. Il faut regarder dans le
dossier channels_per_provider et vous pourrez trouver les chaines que
proposent les différentes sources. Dans une prochaine MAJ, un script
listant tout sera disponible.

Pour la config, c'est pareil. Par défaut, le champ "days" est à 8, il
suffit de copier config_example.json vers config.json et de remplacer le 8
par un 2.

Le dim. 26 sept. 2021 à 17:16, romain211289 ***@***.***> a
écrit :

**Comment by romain211289** [comment]
Oui je viens de voir qu'il y avait d'autres chaines à ajouter. Par contre je viens de voir aussi que je vais avoir du boulot pour modifier ma liste m3u car mes id de chaine ne sont pas toujours les même avec le script.. mais bon le plus gros est fait :) 

Merci pour la réactivité sur les réponses.

**Comment by romain211289** [comment]
Bonjour,

Après quelques jours de test et un peu de config, je confirme que le script est excellent ! Juste pour savoir, est il possible de rajouter des chaines dans "channels_per_provider"  (exemple Prime Vidéo, discovery investigation) ?
Si oui, pouvez vous m'expliquer comment ajouter une chaine à rechercher ? 

Merci !
Bonne journée !

**Comment by racacax** [comment]
Bonjour,
Content que ça fonctionne bien 🙂
Discovery Investigation est bien présente donc pas besoin de la rajouter.
Dans tous les fournisseurs, l'intégralité des chaînes disponibles a été
indiqué.

Pour Prime Video, à moins d'ajouter une nouvelle Source (provider),
impossible de les avoir. Je n'ai trouvé aucune source fiable car ce ne sont
pas des chaînes à proprement parler.

Le dim. 3 oct. 2021 à 12:14, romain211289 ***@***.***> a
écrit :

**Comment by romain211289** [comment]
Bonjour Racacax,

Autant pour moi, il s'agit de Discovery Family, investigation je l'avais trouvé. Bon après rien de grave, ce n'est pas une chaine que je regarde régulièrement.

Par contre rien à voir, mais je voulais savoir si cela serait possible de supprimer automatiquement les fichiers temporaires des chaines et les ancien programmes xmltv (dans le dossier channels et le dossier xmltv) car j'ai l'impression qu'ils restent.. 

Enfin, j'essaye de comprendre ton script pour pouvoir ajouter des sources (channels per provider), et mettre une suppression automatique, je reviendrais vers toi si je bloque. 

Merci pour tout !

**Comment by racacax** [comment]
Bonjour,
À vérifier mais je pense qu'elle est sur Tele7Jours. Mais il doit bien y
avoir d'autre sources sur le net au pire qu'on peut rajouter.

Pour les fichiers temporaires, ils se suppriment au bout de 11 jours à peu
prêt (jours indiqués dans la config + 3 jours)

Le lun. 4 oct. 2021 à 11:28, romain211289 ***@***.***> a
écrit :

**Comment by romain211289** [comment]
Impeccable pour la suppression, je n'avais pas vu dans le script. Tu as pensé à tout !
La source d'EPG la plus complète est https://www.programme-tv.net/ (télé-loisirs). 

Merci pour ta réactivité !
Bonne journée

**Comment by romain211289** [comment]
Une autre source qui pourrait être sympa à ajouter : https://tv-programme.telecablesat.fr/
