### ISSUE TITLE
Nouvelle URL ??

### ISSUE THREAD

**Issue by mikhoul** [racacax/XML-TV-Fr#6]
Y'a t'il une nouvelle URL ou le script est hébergé car http://allfrtv.ga/xmltv.php ne fonctionne pas ?

Salutations ! :octocat:

**Comment by racacax** [comment]
Bonjour,
Je ne génère plus de XML. Il faut télécharger le script et le lancer soit
sur une de tes machines, soit sur un serveur. On a antoinerzad sur mon
Forum (https://forum-racacax.fr.ht) qui utilise le script pour générer un
XML. Bien entendu il n'est pas forcément complet et en utilisant le script
directement, on peut le personnaliser.
