### ISSUE TITLE
OCS & Ciné+

### ISSUE THREAD

**Issue by poiluepistache** [racacax/XML-TV-Fr#68]
Bonjour;

Il y a eu du changement chez OCS et Ciné+ concernant leurs chaines, serait-il possible d'avoir la mise à jour des chaines pour avoir leur programme ? Merci.

https://assistance.canalplus.com/questions/3371090-plan-service-3-juillet-2024
https://assistance.canalplus.com/questions/3371056-savoir-cine-ocs

**Comment by racacax** [comment]
Bonjour,
Merci de l'info ! Je vais regarder ça prochainement, sûrement dans le courant de la semaine prochaine

**Comment by racacax** [comment]
mis à jour dans la version 2.11.6
