### ISSUE TITLE
amélioration

### ISSUE THREAD

**Issue by myB0B** [racacax/XML-TV-Fr#7]
super script
est il possible d'ajouter une option pour intégrer un dummy (fake) epg pour les chaines qui n'en ont pas ?
pour par exemple l'intégration dans jellyfin qui ne gère pas correctement dans le guide les chaines qui n'ont pas d'epg.

**Comment by racacax** [comment]
Merci du soutien. Je note ça pour une prochaine MAJ, ça peut être une bonne idée.

**Comment by racacax** [comment]
fonctionnalité ajoutée

**Comment by myB0B** [comment]
Super! mais ca ne fonctionne pas du tout
1. le xml généré n'est pas formaté correctement et contient des erreurs (sauts de lignes, mauvais alignement, présence de commentaires)
Extrait :
`    <desc lang="fr">1965. Trois jeunes agents du Mossad sont chargés de capturer un criminel nazi. Trente ans plus tard, ils se souviennent de cette mission qui les hante encore.</desc>
    
    
    <icon src="https://proxymedia.woopic.com/340/p/169_EMI_12145544.jpg" />
    
    <rating system="CSA">
      <value>-12</value><icon src="https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Moins12.svg/200px-Moins12.svg.png" /></rating></programme>

<programme start="20211227231100 +0100" stop="20211228000100 +0100" channel="PolarPlus.fr">
`

2. avec l'option dummy a true
par exemple polarTV qui est HS n'est pas ajouter en dummy dans le xml final

ci dessous ma config 
`{
  "days" : 8,
  "cache_max_days": 8,
  "output_path": "./xmltv",
  "time_limit": 0,
  "memory_limit": -1,
  "delete_raw_xml": false,
  "enable_gz": false,
  "enable_zip": false,
  "xml_cache_days": 5,
  "enable_dummy": true,
  "custom_priority_orders": {},
  "guides_to_generate": [{"channels": "./channels.json", "filename": "xmltv.xml"}]
}`

**Comment by myB0B** [comment]
je rajoute ceci : 
en fait le script génère une erreur, la chaine M6Boutique est OK mais les fichiers ne sont pas présents dans le dossiers channels

`[EPG GRAB] Récupération du guide des programmes terminée...
[LOGS]  Export des logs vers logs/logs20211229212014.json
[EXPORT] Génération du XML... (xmltv.xml)
PHP Warning:  fopen(channels/M6Boutique.fr_2021-12-28.xml): Failed to open stream: No such file or directory in /home/xmltv/classes/Utils.php on line 208
PHP Fatal error:  Uncaught TypeError: fgets(): Argument #1 ($stream) must be of type resource, bool given in /home/xmltv/classes/Utils.php:209
Stack trace:
#0 /home/xmltv/classes/Utils.php(209): fgets()
#1 /home/xmltv/script_all.php(37): generateXML()
#2 {main}
  thrown in /home/xmltv/classes/Utils.php on line 209
`

**Comment by racacax** [comment]
Pour le problème du formatage, je n'ai pas de problème. Les commentaires sont formatés correctement, pareil au niveau syntaxe (saut de ligne, ...). 
Pour le dummy, ça se génère bien pour moi. Ta config semble bonne.

Pour M6 Boutique, je n'avais pas ce problème mais je pense savoir d'où ça vient. J'ai corrigé ceci dans la version 1.4.1. Voo retournait tout le temps true même quand HS donc il croyait qu'il y avait un fichier même s'il ne l'avait pas généré.

**Comment by myB0B** [comment]
super, tout fonctionne très bien maintenant
