### ISSUE TITLE
XMLTVFr down?

### ISSUE THREAD

**Issue by s-digweed** [racacax/XML-TV-Fr#71]
Hello,

XMLTVFR.FR seems to be down. Is the site offline? Hope you come back soon :)

Thanks!

**Comment by racacax** [comment]
Hi,
My server host is undergoing an unplanned maintenance. Hopefully it goes fast 🙏 
Sorry for the inconvenience

**Comment by s-digweed** [comment]
No problem, looks to be back. God bless
