### ISSUE TITLE
1.4.1 PHP warning

### ISSUE THREAD

**Issue by myB0B** [racacax/XML-TV-Fr#8]
Petit retour sur la 1.4.1

durant le grab : 

[EPG GRAB] Gong.fr : 2021-12-29 | OK - Bouygues
[EPG GRAB] Gong.fr : 2021-12-30 | OK - Bouygues
[EPG GRAB] Gong.fr : 2021-12-31 | OK - Bouygues
[EPG GRAB] Gong.fr : 2022-01-01 100 %PHP Warning:  Undefined array key 1 in /home/admin/web/srv.fcinc.fr/public_html/xmltv/classes/TeleLoisirs.php on line 34
[EPG GRAB] Gong.fr : 2022-01-01 | OK - TeleLoisirs
[EPG GRAB] Gong.fr : 2022-01-02 | HS
[EPG GRAB] Gong.fr : 2022-01-03 | HS
[EPG GRAB] Gong.fr : 2022-01-04 | HS
[EPG GRAB] Gong.fr : 2022-01-05 | HS
[EPG GRAB] Gong.fr : 2022-01-06 | HS

**Comment by racacax** [comment]
Bien vu,
Parfois l'EPG est incomplet pour un jour donné sur TeleLoisirs (souvent quand une chaine propose une programmation sur quelques jours notamment). Je corrige ça
